### ISSUE TITLE
【作业贴】移应171 03 猜数字实现

### ISSUE THREAD

**Issue by mejiwef** [BestACE/fed#424]
1

**Comment by FISHTIANTIAN** [comment]
20-张天https://bentuotuo.github.io/web/index.html

**Comment by mejiwef** [comment]
49 陈佳明 https://mejiwef.github.io/homework/2018/09/14/index.html

**Comment by nixiaoliang** [comment]
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>猜数字游戏</title>
		<style type="text/css">
			.Number{
				width:300px;
				height:300px;
				margin: auto;
				position:absolute;
				left:0;
				right:0;
				top:0;
				bottom:0;
				border:2px solid #000;
			}
			.Nmuber h2{
				text-align:center;
			}
			.Number .C{
				width:252px;
				margin:auto;
			}
			.Number #numInput{
				border:none;
				outline:none;
				border:2px solid #000;
				width:186px;
				height:30px;
				border-radius:20px 0 0 20px;
				text-indent:15px;
			}
			.Number #Gusee{
				border: none;
				outline: none;
				background: none;
				border: 1px solid #000;
				width: 55px;
				height:21px;
				border-radius:0px 20px 20px 0px;
				position:relative;
				left:-6px;
				top:1px;
			}
			.Number.tip{
				font-size: 14px;
				color: #666;
			}
			.tip p{
				margin:6px 0;
			}
		</style>
	</head>
	<body>
		<div class="Number">
			
			<h2 class="title">猜数字游戏</h2>
			<div class="C">
				<input type="number" placeholder="0110整数，3次机会" />
				<input type="button" id="Guess" value="猜数字" />
				
			</div>
			<div class="tip">
				<p>剩下次数：3</p>
				<p>猜测历史</p>
				<p id="tipText"></p>
			</div>
		</div>
		<script type="text/javascript">
			var targetNum=parserInt(Math.random()*11);
			console.log(targetNum);
			var guseeTimes=3;
			var oNumInput=document.getElementById("numInput");
			var oBtnGuess=document.getElementById("Guess");
			var oTipText=document.getElementById("tipText");
			function guess(){
				
				if(oNumInput.value>targetNum){
					oTipText.innerHTML="这次猜测的X，有点偏大"
					ONumInput.value=""
					oNumInput.focus
				}else{
					
				}
			}
			
		</script>
	</body>
</html>

**Comment by Doinbbb** [comment]
11 王志文https://doinbbb.github.io/%E7%8C%9C%E6%95%B0%E5%AD%97.html

**Comment by chenzhiwei111** [comment]
32陈志伟https://chenzhiwei111.github.io/czw/index.html

**Comment by HUYI-R** [comment]
38---楼思宏https://fengxiaozaici.github.io/feng/enjj/index.html

**Comment by zq0951** [comment]
07-张舒鹏https://zq0951.github.io/猜数字.html

**Comment by ljq6666** [comment]
29李佳奇https://ljq6666.github.io/qqq/index.html

**Comment by dameinan** [comment]
40-姚海南https://dameinan.github.io/hello/rng.html

**Comment by zengrichang** [comment]
48曾日昌https://zengrichang.github.io/sada/index.html

**Comment by wode98k** [comment]
44傅化韩 https://wode98k.github.io/number/xixixxx.html

**Comment by 15968191839** [comment]
03 楼競恒  https://15968191839.github.io/9.14/index.html

**Comment by LINWQG** [comment]
46林文青https://piggss.github.io/cshuz/index.html

**Comment by zgwh** [comment]
18诸葛文瀚 https://zgwh.github.io/caishuzi/index.html

**Comment by Yufendian** [comment]
42 贺郑鹏https://yufendian.github.io/Yufendian01/index.html

**Comment by yiting63** [comment]
39.边逸婷https://yiting63.github.io/shuzi.html

**Comment by zptcmt** [comment]
25张明https://zptcmt.github.io/18.9-19.1/18.9.14/guessNumber.html

**Comment by sjkkkk** [comment]
19 盛佳康https://sjkkkk.github.io/caishuzi/caishuzi.html

**Comment by lasacacias** [comment]
17叶靖 https://lasacacias.github.io/guessnumber.html

**Comment by qiukaibing** [comment]
36 裘凯炳 http://qiukaibing.github.io/qqq/index.html

**Comment by jeffchenxin** [comment]
10 陈昕https://jeffchenxin.github.io/Cx-js.github.io/three/index.html

**Comment by zzzzzzzzzc** [comment]
05-赵琛https://zzzzzzzzzc.github.io/zc.html

**Comment by diviner1121** [comment]
27 戴甄  https://diviner1121.github.io/Dz/csz.html

**Comment by bhm37** [comment]
37 鲍华明https://bhm37.github.io/czyx/index.html

**Comment by Yztttttt** [comment]
08-严振焘https://yztttttt.github.io/yzt.html

**Comment by 1647502335** [comment]
04周皓天https://1647502335.github.io/yx.html

**Comment by 20170608133** [comment]
33张铭泳https://20170608133.github.io/DKD/

**Comment by zbb1299316394** [comment]
22朱浜浜https://zbb1299316394.github.io/%E6%B8%B8%E6%88%8F/index.html

**Comment by weirdo1998** [comment]
30邵丽君https://weirdo1998.github.io/猜数字/index.html

**Comment by 377a61** [comment]
13王露露https://377a61.github.io/%E7%8C%9C%E6%95%B0%E5%AD%97%E6%B8%B8%E6%88%8F.html

**Comment by songdadacarry** [comment]
24-宋佳军 https://songdadacarry.github.io/sss/index.html

**Comment by cveivei** [comment]
045陈薇薇https://cveivei.github.io/JavaScript/JavaScript/choujiang/indent.html

**Comment by Mcccccccc** [comment]
21 傅全超 https://mcccccccc.github.io/%E5%A4%A7%E5%A4%A7%E5%A4%A7%E5%A4%A7%E8%B6%85.htm

**Comment by 1103070072z** [comment]
14周家骏https://1103070072z.github.io/csss/new_file.html

**Comment by yingxiaogan** [comment]
26 应小刚 https://yingxiaogan.github.io/yxg-javaScript.github.io/xg/index.html

**Comment by tonggechiou** [comment]
43 潘一炜 https://tonggechiou.github.io/%E7%8C%9C%E6%95%B0%E5%AD%97/index.html

**Comment by lljzkadrasd** [comment]
31王泽钰https://lljzkadrasd.github.io/awe/index.html

**Comment by Yakunn** [comment]
06 李亚坤https://yakunn.github.io/hello/index.html

**Comment by HuaJiW** [comment]
50陈家辉https://huajiw.github.io/ewq/index.html

**Comment by wudikuangkuang** [comment]
35 叶通  https://wudikuangkuang.github.io/zhexueshigehaodongxi/jfla/new_file.html

**Comment by x20170608115** [comment]
15徐效宇https://x20170608115.github.io/cai/index.html

**Comment by wozhemenuan** [comment]
47赵日旭 https://wozhemenuan.github.io/sss/index.html

**Comment by 7TS-W** [comment]
12吴行文https://7ts-w.github.io/index.html

**Comment by tangzhuyin** [comment]
23 唐寅  https://tangzhuyin.github.io/ty.html

**Comment by zptcsoft** [comment]
郑威强、卢耀阳、罗爽未交。
